### ISSUE TITLE
is there any limitation about the pdf file?

### ISSUE THREAD

**Issue by SanjayYDas** [GURPREETKAURJETHRA/Multi-PDFs_ChatApp_AI-Agent#2]
I am trying to build a pdf query chat bot using google genai , FAISS and GoogleGenerativeAIEmbeddings. when i give a pdf of 25 page it is showing a error 
ie IndexError: list index out of range
![image](https://github.com/GURPREETKAURJETHRA/Multi-PDFs_ChatApp_AI-Agent/assets/90176407/c4692ffe-e067-4d4b-b7b4-547e97558520)
For you reference i have attached a ss

**Comment by GURPREETKAURJETHRA** [comment]
No, it's working absolutely fine with multiple pdfs n multiple pages of pdf without limitation. I just checked again with 53 pages pdf. It's working fine. Please recheck code once.
